name: nightly-update
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  nightly-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: sudo apt-get install lftp
      - name: update
        run: ./update.sh
      - name: push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email ""
          git add .
          git commit -m "nightly update"
          git push
